# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GsTCgw6nPQQ1hPxuhVAgzqEqlm-oXDp2
"""

!pip install torch torchvision scikit-learn pandas numpy matplotlib pillow -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import torch
import torch.nn as nn
import torchvision.models as models
import torchvision.transforms as transforms
from PIL import Image
from torch.utils.data import Dataset, DataLoader
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

# Download the Houses Dataset (images + tabular)
!git clone https://github.com/emanhamed/Houses-dataset.git

# Load tabular info
df = pd.read_csv('Houses-dataset/Houses Dataset/HousesInfo.txt',
                 sep=' ', header=None,
                 names=['bedrooms','bathrooms','area','zipcode','price'])

# Link frontal images only (each house has 4 views; we use frontal)
img_dir = 'Houses-dataset/Houses Dataset'
df['image_path'] = [os.path.join(img_dir, f"{i+1}_frontal.jpg") for i in range(len(df))]

# Keep only rows where image exists
df = df[df['image_path'].apply(os.path.exists)].reset_index(drop=True)

print(f"Samples: {len(df)}")
print(df.head())

# Features
X_tab = df[['bedrooms','bathrooms','area','zipcode']].copy()

# Scale numerical, One-Hot encode zipcode
tabular_transform = ColumnTransformer([
    ('num', StandardScaler(), ['bedrooms','bathrooms','area']),
    ('cat', OneHotEncoder(sparse_output=False, handle_unknown='ignore'), ['zipcode'])
])

X_tab_processed = tabular_transform.fit_transform(X_tab).astype(np.float32)

# Scale target (price) for stable training
price_scaler = StandardScaler()
y = df['price'].values.reshape(-1, 1)
y_scaled = price_scaler.fit_transform(y).flatten().astype(np.float32)

# Train/Test split
train_idx, test_idx = train_test_split(
    np.arange(len(df)), test_size=0.2, random_state=42
)

print(f"Tabular feature dim: {X_tab_processed.shape[1]}")

class HouseDataset(Dataset):
    def __init__(self, df, tabular, targets, indices, transform=None):
        self.df = df.iloc[indices].reset_index(drop=True)
        self.tabular = tabular[indices]
        self.targets = targets[indices]
        self.transform = transform

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        img = Image.open(self.df.iloc[idx]['image_path']).convert('RGB')
        if self.transform:
            img = self.transform(img)

        tab = torch.tensor(self.tabular[idx], dtype=torch.float32)
        tgt = torch.tensor(self.targets[idx], dtype=torch.float32)
        return img, tab, tgt

# ImageNet normalization for ResNet
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

train_ds = HouseDataset(df, X_tab_processed, y_scaled, train_idx, transform)
test_ds  = HouseDataset(df, X_tab_processed, y_scaled, test_idx, transform)

train_loader = DataLoader(train_ds, batch_size=16, shuffle=True)
test_loader  = DataLoader(test_ds, batch_size=16, shuffle=False)

class MultimodalRegressor(nn.Module):
    def __init__(self, tabular_dim):
        super().__init__()
        # IMAGE BRANCH: Pretrained ResNet18, frozen backbone
        self.image_encoder = models.resnet18(pretrained=True)
        img_feat_dim = self.image_encoder.fc.in_features
        self.image_encoder.fc = nn.Identity()  # remove final FC

        for param in self.image_encoder.parameters():
            param.requires_grad = False

        # TABULAR BRANCH: Small MLP
        self.tabular_encoder = nn.Sequential(
            nn.Linear(tabular_dim, 64),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(64, 32),
            nn.ReLU()
        )

        # FUSION HEAD
        self.head = nn.Sequential(
            nn.Linear(img_feat_dim + 32, 128),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(128, 1)
        )

    def forward(self, image, tabular):
        img_feat = self.image_encoder(image)      # [B, 512]
        tab_feat = self.tabular_encoder(tabular)  # [B, 32]
        fused = torch.cat([img_feat, tab_feat], dim=1)
        return self.head(fused).view(-1)          # [B]

model = MultimodalRegressor(tabular_dim=X_tab_processed.shape[1]).to(device)
print(f"Total params: {sum(p.numel() for p in model.parameters()):,}")
print(f"Trainable params: {sum(p.numel() for p in model.parameters() if p.requires_grad):,}")

criterion = nn.MSELoss()
optimizer = torch.optim.Adam(
    filter(lambda p: p.requires_grad, model.parameters()),
    lr=1e-3
)

epochs = 50

for epoch in range(epochs):
    model.train()
    running_loss = 0.0

    for images, tabular, targets in train_loader:
        images, tabular, targets = images.to(device), tabular.to(device), targets.to(device)

        optimizer.zero_grad()
        preds = model(images, tabular)
        loss = criterion(preds, targets)
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * images.size(0)

    epoch_loss = running_loss / len(train_loader.dataset)

    if (epoch + 1) % 10 == 0:
        print(f"Epoch {epoch+1:02d} | Loss: {epoch_loss:.4f}")

model.eval()
all_preds, all_targets = [], []

with torch.no_grad():
    for images, tabular, targets in test_loader:
        images, tabular = images.to(device), tabular.to(device)
        outputs = model(images, tabular).cpu().numpy()

        all_preds.extend(outputs)
        all_targets.extend(targets.numpy())

# Inverse transform to get real dollar values
preds_inv = price_scaler.inverse_transform(np.array(all_preds).reshape(-1, 1)).flatten()
targets_inv = price_scaler.inverse_transform(np.array(all_targets).reshape(-1, 1)).flatten()

mae = mean_absolute_error(targets_inv, preds_inv)
rmse = np.sqrt(mean_squared_error(targets_inv, preds_inv))

print(f"MAE:  ${mae:,.2f}")
print(f"RMSE: ${rmse:,.2f}")

# ── Plot ─────────────────────────────────────────────────────────
plt.figure(figsize=(6, 6))
plt.scatter(targets_inv, preds_inv, alpha=0.7, edgecolors='white', color='#3b6fd4')
plt.plot([targets_inv.min(), targets_inv.max()],
         [targets_inv.min(), targets_inv.max()],
         'r--', lw=2)
plt.xlabel('Actual Price ($)', fontsize=11)
plt.ylabel('Predicted Price ($)', fontsize=11)
plt.title('Multimodal Model: Actual vs Predicted', fontsize=12)
plt.tight_layout()
plt.savefig('multimodal_results.png', dpi=150)
plt.show()

