# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zosd3Jf7FShpoxjQKVvZEM2xo5nrLMCu
"""

from datasets import load_dataset
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# ── Load AG News Dataset ──────────────────────────────────────────
dataset = load_dataset("ag_news")

print("Dataset Structure:")
print(dataset)

# ── Explore the Data ─────────────────────────────────────────────
print("\nTraining samples:", len(dataset['train']))
print("Testing samples:", len(dataset['test']))

# View sample entries
print("\nSample Data:")
for i in range(3):
    print(f"\nText: {dataset['train'][i]['text']}")
    print(f"Label: {dataset['train'][i]['label']}")

# ── Label Information ─────────────────────────────────────────────
label_names = dataset['train'].features['label'].names
print(f"\nLabel Names: {label_names}")
# Output: ['World', 'Sports', 'Business', 'Sci/Tech']

# ── Class Distribution ────────────────────────────────────────────
train_df = pd.DataFrame(dataset['train'])
train_df['label_name'] = train_df['label'].map(dict(enumerate(label_names)))

plt.figure(figsize=(8, 5))
sns.countplot(data=train_df, x='label_name', palette='viridis')
plt.title('Class Distribution in AG News Dataset')
plt.xlabel('Category')
plt.ylabel('Count')
plt.savefig('class_distribution.png')
plt.show()

print("\nClass Distribution:")
print(train_df['label_name'].value_counts())

from transformers import BertTokenizer
from datasets import DatasetDict

# ── Load BERT Tokenizer ───────────────────────────────────────────
MODEL_NAME = "bert-base-uncased"
tokenizer = BertTokenizer.from_pretrained(MODEL_NAME)

# ── Define Max Length ─────────────────────────────────────────────
MAX_LENGTH = 128  # News headlines are short

# ── Tokenization Function ─────────────────────────────────────────
def tokenize_function(examples):
    return tokenizer(
        examples['text'],
        padding='max_length',      # Pad to MAX_LENGTH
        truncation=True,           # Truncate if longer
        max_length=MAX_LENGTH,
        return_tensors=None        # Return lists (for datasets)
    )

# ── Apply Tokenization ────────────────────────────────────────────
print("Tokenizing dataset...")
tokenized_datasets = dataset.map(
    tokenize_function,
    batched=True,           # Process in batches (faster)
    batch_size=1000,
    remove_columns=['text'] # Remove raw text column
)

# ── Set Format for PyTorch ────────────────────────────────────────
tokenized_datasets.set_format(
    type='torch',
    columns=['input_ids', 'attention_mask', 'token_type_ids', 'label']
)

print("\nTokenized Dataset:")
print(tokenized_datasets)

# ── Verify Sample ─────────────────────────────────────────────────
sample = tokenized_datasets['train'][0]
print(f"\nInput IDs shape: {sample['input_ids'].shape}")
print(f"Attention Mask shape: {sample['attention_mask'].shape}")
print(f"Label: {sample['label']}")

# ── Use Smaller Subset for Faster Training (Optional) ─────────────
# Remove these lines if you want full training
small_train = tokenized_datasets['train'].shuffle(seed=42).select(range(10000))
small_test  = tokenized_datasets['test'].shuffle(seed=42).select(range(2000))

tokenized_datasets = DatasetDict({
    'train': small_train,
    'test':  small_test
})
print(f"\nUsing subset - Train: {len(small_train)}, Test: {len(small_test)}")

from transformers import (
    BertForSequenceClassification,
    TrainingArguments,
    Trainer,
    DataCollatorWithPadding
)
import numpy as np
from sklearn.metrics import accuracy_score, f1_score, classification_report
import evaluate

# ── Load Pre-trained BERT Model ───────────────────────────────────
NUM_LABELS = 4  # World, Sports, Business, Sci/Tech

model = BertForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=NUM_LABELS,
    id2label={i: name for i, name in enumerate(label_names)},
    label2id={name: i for i, name in enumerate(label_names)}
)

print(f"Model loaded with {NUM_LABELS} output labels")
print(f"Total parameters: {model.num_parameters():,}")
print(f"Trainable parameters: {sum(p.numel() for p in model.parameters() if p.requires_grad):,}")

# ── Define Evaluation Metrics ─────────────────────────────────────
accuracy_metric = evaluate.load("accuracy")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)

    accuracy = accuracy_score(labels, predictions)
    f1_macro = f1_score(labels, predictions, average='macro')
    f1_weighted = f1_score(labels, predictions, average='weighted')

    return {
        'accuracy': accuracy,
        'f1_macro': f1_macro,
        'f1_weighted': f1_weighted
    }

# ── Training Arguments ────────────────────────────────────────────
training_args = TrainingArguments(
    output_dir='./results',              # Save directory
    num_train_epochs=3,                  # Number of epochs
    per_device_train_batch_size=16,      # Batch size for training
    per_device_eval_batch_size=32,       # Batch size for evaluation
    warmup_steps=500,                    # Warmup for learning rate
    weight_decay=0.01,                   # Regularization
    learning_rate=2e-5,                  # BERT fine-tuning LR
    logging_dir='./logs',                # Logging directory
    logging_steps=100,                   # Log every 100 steps
    eval_strategy='epoch',         # Evaluate after each epoch
    save_strategy='epoch',               # Save after each epoch
    load_best_model_at_end=True,         # Load best model
    metric_for_best_model='accuracy',    # Metric to select best model
    greater_is_better=True,
    report_to='none',                    # Disable wandb
    fp16=torch.cuda.is_available(),      # Mixed precision if GPU
)

# ── Data Collator ─────────────────────────────────────────────────
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)
# ── Initialize Trainer ────────────────────────────────────────────
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets['test'],
    processing_class=tokenizer,      # <--- CHANGED 'tokenizer' to 'processing_class'
    data_collator=data_collator,
    compute_metrics=compute_metrics
)

# ── Start Training ────────────────────────────────────────────────
print("\n" + "="*50)
print("Starting Fine-Tuning...")
print("="*50)

train_result = trainer.train()

print("\nTraining Complete!")
print(f"Training Loss: {train_result.training_loss:.4f}")

# ── Save the Model ────────────────────────────────────────────────
model.save_pretrained('./saved_model')
tokenizer.save_pretrained('./saved_model')
print("\nModel saved to './saved_model'")

!pip install evaluate

!pip install transformers datasets torch scikit-learn gradio streamlit
!pip install accelerate evaluate
!pip install pandas numpy matplotlib seaborn

from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# ── Run Evaluation ────────────────────────────────────────────────
print("\n" + "="*50)
print("Evaluating Model...")
print("="*50)

eval_results = trainer.evaluate()

print("\nEvaluation Results:")
for key, value in eval_results.items():
    print(f"  {key}: {value:.4f}")

# ── Detailed Classification Report ───────────────────────────────
predictions = trainer.predict(tokenized_datasets['test'])
predicted_labels = np.argmax(predictions.predictions, axis=-1)
true_labels = predictions.label_ids

print("\nDetailed Classification Report:")
print(classification_report(
    true_labels,
    predicted_labels,
    target_names=label_names
))

# ── Confusion Matrix ──────────────────────────────────────────────
cm = confusion_matrix(true_labels, predicted_labels)

plt.figure(figsize=(8, 6))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=label_names,
    yticklabels=label_names
)
plt.title('Confusion Matrix - AG News Classifier')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.tight_layout()
plt.savefig('confusion_matrix.png')
plt.show()

# ── Per-class Accuracy ────────────────────────────────────────────
print("\nPer-class Accuracy:")
for i, name in enumerate(label_names):
    class_acc = cm[i][i] / cm[i].sum()
    print(f"  {name}: {class_acc:.4f} ({class_acc*100:.2f}%)")

# ── Training History Plot ─────────────────────────────────────────
# Extract loss history from trainer logs
train_history = trainer.state.log_history

train_losses = [x['loss'] for x in train_history if 'loss' in x]
eval_losses  = [x['eval_loss'] for x in train_history if 'eval_loss' in x]

plt.figure(figsize=(10, 4))
plt.subplot(1, 2, 1)
plt.plot(train_losses, label='Train Loss', color='blue')
plt.title('Training Loss')
plt.xlabel('Steps')
plt.ylabel('Loss')
plt.legend()

plt.subplot(1, 2, 2)
eval_accs = [x['eval_accuracy'] for x in train_history if 'eval_accuracy' in x]
plt.plot(eval_accs, label='Validation Accuracy', color='green', marker='o')
plt.title('Validation Accuracy per Epoch')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.tight_layout()
plt.savefig('training_history.png')
plt.show()

import gradio as gr
import torch
import torch.nn.functional as F
from transformers import BertForSequenceClassification, BertTokenizer

# Load Model
model_path = './saved_model'
tokenizer = BertTokenizer.from_pretrained(model_path)
model = BertForSequenceClassification.from_pretrained(model_path)
model.eval()

categories = ['World', 'Sports', 'Business', 'Sci/Tech']

def classify_news(text):
    if not text.strip():
        return {cat: 0.0 for cat in categories}

    inputs = tokenizer(text, return_tensors='pt', max_length=128, padding=True, truncation=True)

    with torch.no_grad():
        logits = model(**inputs).logits
        probs = F.softmax(logits, dim=-1)[0]

    return {cat: float(prob) for cat, prob in zip(categories, probs)}

# Build minimalist UI
with gr.Blocks(theme=gr.themes.Default()) as demo:
    gr.Markdown("# News Topic Classifier")
    gr.Markdown("Classify news headlines into World, Sports, Business, or Sci/Tech categories.")

    with gr.Row():
        with gr.Column():
            text_input = gr.Textbox(
                label="News Headline",
                placeholder="Enter a headline here...",
                lines=3
            )
            submit_btn = gr.Button("Classify", variant="primary")

        with gr.Column():
            label_output = gr.Label(label="Prediction Confidence")

    gr.Examples(
        examples=[
            "NASA launches new Mars rover to search for ancient life",
            "Stock market hits record high amid strong earnings reports",
            "World Cup final draws record viewership across the globe",
            "UN Security Council meets to discuss Middle East tensions"
        ],
        inputs=text_input,
        outputs=label_output,
        fn=classify_news
    )

    # Trigger classification on button click or pressing Enter
    submit_btn.click(classify_news, inputs=text_input, outputs=label_output)
    text_input.submit(classify_news, inputs=text_input, outputs=label_output)

# Launch (generates public URL in Colab)
demo.launch(share=True)

