# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R8JIErsC3tVvn2X02jfKdLq017xAsVsL
"""

!pip install scikit-learn pandas numpy matplotlib seaborn joblib

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.metrics import (accuracy_score, f1_score, classification_report,
                             confusion_matrix, roc_auc_score, roc_curve)
import joblib
import warnings
warnings.filterwarnings('ignore')

print("All libraries imported successfully!")

# ── Load Telco Churn Dataset ──────────────────────────────────────
url = "https://raw.githubusercontent.com/IBM/telco-customer-churn-on-icp4d/master/data/Telco-Customer-Churn.csv"
df = pd.read_csv(url)

print("Shape:", df.shape)
print("\nFirst 5 rows:")
df.head()

# ── Basic Info ────────────────────────────────────────────────────
print("Dataset Info:")
print(df.info())

print("\nMissing Values:")
print(df.isnull().sum())

print("\nTarget Distribution:")
print(df['Churn'].value_counts())
print(f"\nChurn Rate: {df['Churn'].value_counts(normalize=True)['Yes']*100:.1f}%")

# ── Visualizations ────────────────────────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(15, 4))

# Churn Distribution
df['Churn'].value_counts().plot(
    kind='bar', ax=axes[0],
    color=['#3b6fd4', '#e05c5c'],
    edgecolor='white'
)
axes[0].set_title('Churn Distribution')
axes[0].set_xlabel('Churn')
axes[0].set_ylabel('Count')
axes[0].tick_params(rotation=0)

# Tenure vs Churn
df.groupby('Churn')['tenure'].plot(
    kind='hist', ax=axes[1],
    alpha=0.7, bins=30,
    color=['#3b6fd4', '#e05c5c']
)
axes[1].set_title('Tenure by Churn')
axes[1].set_xlabel('Tenure (months)')
axes[1].legend(['No Churn', 'Churn'])

# Monthly Charges vs Churn
df.boxplot(column='MonthlyCharges', by='Churn', ax=axes[2])
axes[2].set_title('Monthly Charges by Churn')
axes[2].set_xlabel('Churn')

plt.tight_layout()
plt.savefig('eda_plots.png', dpi=150)
plt.show()

# ── Clean Data ────────────────────────────────────────────────────

# Drop customerID (not useful)
df.drop('customerID', axis=1, inplace=True)

# Fix TotalCharges (has spaces, should be numeric)
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

# Fill missing TotalCharges with median
df['TotalCharges'].fillna(df['TotalCharges'].median(), inplace=True)

# Encode target variable
df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0})

print("Target encoded: Yes=1, No=0")
print(df['Churn'].value_counts())

# ── Define Features ───────────────────────────────────────────────

# Separate features and target
X = df.drop('Churn', axis=1)
y = df['Churn']

# Identify column types
numerical_cols = X.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_cols = X.select_dtypes(include=['object']).columns.tolist()

print(f"Numerical columns ({len(numerical_cols)}): {numerical_cols}")
print(f"\nCategorical columns ({len(categorical_cols)}): {categorical_cols}")

# ── Train Test Split ──────────────────────────────────────────────
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y        # Keep same churn ratio in both splits
)

print(f"Training set:   {X_train.shape}")
print(f"Testing set:    {X_test.shape}")
print(f"\nTrain churn rate: {y_train.mean()*100:.1f}%")
print(f"Test churn rate:  {y_test.mean()*100:.1f}%")

# ── Preprocessing Pipeline ────────────────────────────────────────

# Numerical: Scale features
numerical_transformer = Pipeline(steps=[
    ('scaler', StandardScaler())
])

# Categorical: One-hot encode
categorical_transformer = Pipeline(steps=[
    ('encoder', OneHotEncoder(handle_unknown='ignore', drop='first'))
])

# Combine both transformers
preprocessor = ColumnTransformer(transformers=[
    ('num', numerical_transformer, numerical_cols),
    ('cat', categorical_transformer, categorical_cols)
])

print("Preprocessor built successfully!")
print("\nSteps:")
print("  Numerical  → StandardScaler")
print("  Categorical → OneHotEncoder")

# ── Full Pipelines (Preprocessor + Model) ────────────────────────

# Pipeline 1: Logistic Regression
lr_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(
        random_state=42,
        max_iter=1000
    ))
])

# Pipeline 2: Random Forest
rf_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(
        random_state=42,
        n_jobs=-1
    ))
])

print("Pipelines built!")
print("\nLogistic Regression Pipeline:")
print(lr_pipeline)
print("\nRandom Forest Pipeline:")
print(rf_pipeline)

# ── Train Logistic Regression (Quick Baseline) ────────────────────
print("Training Logistic Regression baseline...")
lr_pipeline.fit(X_train, y_train)
lr_base_score = lr_pipeline.score(X_test, y_test)
print(f"Baseline Accuracy: {lr_base_score:.4f}")

# ── GridSearchCV for Logistic Regression ──────────────────────────
lr_param_grid = {
    'classifier__C': [0.01, 0.1, 1, 10],
    'classifier__solver': ['lbfgs', 'liblinear'],
    'classifier__penalty': ['l2']
}

lr_grid_search = GridSearchCV(
    lr_pipeline,
    lr_param_grid,
    cv=5,                   # 5-fold cross validation
    scoring='f1',           # Optimize for F1
    n_jobs=-1,              # Use all CPU cores
    verbose=1
)

print("Running GridSearchCV for Logistic Regression...")
lr_grid_search.fit(X_train, y_train)

print(f"\nBest Parameters: {lr_grid_search.best_params_}")
print(f"Best CV F1 Score: {lr_grid_search.best_score_:.4f}")

# ── GridSearchCV for Random Forest ───────────────────────────────
rf_param_grid = {
    'classifier__n_estimators': [100, 200],
    'classifier__max_depth': [5, 10, None],
    'classifier__min_samples_split': [2, 5],
    'classifier__min_samples_leaf': [1, 2]
}

rf_grid_search = GridSearchCV(
    rf_pipeline,
    rf_param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

print("Running GridSearchCV for Random Forest...")
rf_grid_search.fit(X_train, y_train)

print(f"\nBest Parameters: {rf_grid_search.best_params_}")
print(f"Best CV F1 Score: {rf_grid_search.best_score_:.4f}")

# ── Get Best Models ───────────────────────────────────────────────
best_lr = lr_grid_search.best_estimator_
best_rf = rf_grid_search.best_estimator_

# ── Predictions ───────────────────────────────────────────────────
lr_preds = best_lr.predict(X_test)
rf_preds = best_rf.predict(X_test)

lr_probs = best_lr.predict_proba(X_test)[:, 1]
rf_probs = best_rf.predict_proba(X_test)[:, 1]

# ── Metrics ───────────────────────────────────────────────────────
def evaluate_model(name, y_true, y_pred, y_prob):
    print(f"\n{'='*50}")
    print(f"  {name}")
    print(f"{'='*50}")
    print(f"  Accuracy:  {accuracy_score(y_true, y_pred):.4f}")
    print(f"  F1 Score:  {f1_score(y_true, y_pred):.4f}")
    print(f"  ROC-AUC:   {roc_auc_score(y_true, y_prob):.4f}")
    print(f"\n  Classification Report:")
    print(classification_report(y_true, y_pred, target_names=['No Churn', 'Churn']))

evaluate_model("Logistic Regression", y_test, lr_preds, lr_probs)
evaluate_model("Random Forest",       y_test, rf_preds, rf_probs)

# ── Confusion Matrices ────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(12, 4))

for ax, preds, title in zip(
    axes,
    [lr_preds, rf_preds],
    ['Logistic Regression', 'Random Forest']
):
    cm = confusion_matrix(y_test, preds)
    sns.heatmap(
        cm, annot=True, fmt='d',
        cmap='Blues', ax=ax,
        xticklabels=['No Churn', 'Churn'],
        yticklabels=['No Churn', 'Churn']
    )
    ax.set_title(f'{title} - Confusion Matrix')
    ax.set_ylabel('True Label')
    ax.set_xlabel('Predicted Label')

plt.tight_layout()
plt.savefig('confusion_matrices.png', dpi=150)
plt.show()

# ── ROC Curves ───────────────────────────────────────────────────
plt.figure(figsize=(8, 5))

for probs, label, color in zip(
    [lr_probs, rf_probs],
    ['Logistic Regression', 'Random Forest'],
    ['#3b6fd4', '#e05c5c']
):
    fpr, tpr, _ = roc_curve(y_test, probs)
    auc = roc_auc_score(y_test, probs)
    plt.plot(fpr, tpr, label=f'{label} (AUC={auc:.3f})', color=color, lw=2)

plt.plot([0,1], [0,1], 'k--', lw=1)
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve Comparison')
plt.legend()
plt.tight_layout()
plt.savefig('roc_curves.png', dpi=150)
plt.show()

# ── Feature Importance (Random Forest) ───────────────────────────
rf_classifier = best_rf.named_steps['classifier']
feature_names = (
    numerical_cols +
    list(best_rf.named_steps['preprocessor']
         .transformers_[1][1]
         .named_steps['encoder']
         .get_feature_names_out(categorical_cols))
)

importances = pd.Series(
    rf_classifier.feature_importances_,
    index=feature_names
).sort_values(ascending=False)[:10]

plt.figure(figsize=(9, 5))
importances.plot(kind='bar', color='#3b6fd4', edgecolor='white')
plt.title('Top 10 Feature Importances - Random Forest')
plt.ylabel('Importance Score')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.savefig('feature_importance.png', dpi=150)
plt.show()

# ── Select Best Model ─────────────────────────────────────────────
lr_f1 = f1_score(y_test, lr_preds)
rf_f1 = f1_score(y_test, rf_preds)

best_model = best_rf if rf_f1 > lr_f1 else best_lr
best_name  = "Random Forest" if rf_f1 > lr_f1 else "Logistic Regression"

print(f"Best Model: {best_name}")
print(f"F1 Score:   {max(lr_f1, rf_f1):.4f}")

# ── Export Pipeline ───────────────────────────────────────────────
joblib.dump(best_model, 'churn_pipeline.pkl')
print("\nPipeline saved as 'churn_pipeline.pkl'")

# ── Verify Export ─────────────────────────────────────────────────
loaded_pipeline = joblib.load('churn_pipeline.pkl')
verify_preds = loaded_pipeline.predict(X_test)
print(f"Loaded pipeline accuracy: {accuracy_score(y_test, verify_preds):.4f}")
print("Export verified successfully!")

# ── Test Pipeline on New Data ─────────────────────────────────────
# Simulate a new customer
new_customer = pd.DataFrame([{
    'gender': 'Male',
    'SeniorCitizen': 0,
    'Partner': 'Yes',
    'Dependents': 'No',
    'tenure': 12,
    'PhoneService': 'Yes',
    'MultipleLines': 'No',
    'InternetService': 'Fiber optic',
    'OnlineSecurity': 'No',
    'OnlineBackup': 'No',
    'DeviceProtection': 'No',
    'TechSupport': 'No',
    'StreamingTV': 'Yes',
    'StreamingMovies': 'Yes',
    'Contract': 'Month-to-month',
    'PaperlessBilling': 'Yes',
    'PaymentMethod': 'Electronic check',
    'MonthlyCharges': 85.0,
    'TotalCharges': 1020.0
}])

prediction = loaded_pipeline.predict(new_customer)[0]
probability = loaded_pipeline.predict_proba(new_customer)[0][1]

print(f"\nNew Customer Prediction:")
print(f"  Churn: {'YES' if prediction == 1 else 'NO'}")
print(f"  Churn Probability: {probability*100:.1f}%")

